name: CI/CD para React com GitHub Actions e SonarCloud

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build React application
        run: npm run build

      - name: Create GitHub release
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: ./build

      - name: Request approval for deployment (opcional)
        if: github.event.pull_request.head.repo.owner == github.event.repo.owner && github.event.pull_request.head.repo.name == github.event.repo.name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - name: Request approval for deployment
            uses: actions/github-script@v6
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                github.repos.createOrUpdateEnvironment(
                  owner: ${{ github.context.repo.owner }},
                  repo: ${{ github.context.repo.repo }},
                  environment: production,
                  request_reviews: {
                    teams: [
                      "seu-time-github"
                    ],
                    users: [
                      "usuario-github"
                    ]
                  }
                )

      - name: Generate code coverage report (opcional)
        run: npm run coverage

      - name: Analyze code with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Deploy to staging environment
        if: github.event.pull_request.head.repo.owner == github.event.pull_request.head.repo.name && github.event

      - name: Notify on failure (opcional)
        if: failure()
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        steps:
          - name: Send email notification
            uses: dawidd6/sendgrid-action@v1
            with:
              api_key: ${{ secrets.SENDGRID_API_KEY }}
              from: "seu-nome@seudominio.com"
              to: ${{ secrets.RECIPIENT_EMAIL }}
              subject: "Falha no pipeline de CI/CD para React"
              body: |
                O pipeline de CI/CD para o projeto React falhou na etapa "${{ steps.name }}".

                Acesse o GitHub Actions para mais detalhes: https://github.com/${{ github.context.repo.owner }}/${{ github.context.repo.repo }}/actions/runs/${{ github.context.workflow_id }}