name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Notify on failure
        if: failure()   # Executar somente se algum dos passos anteriores falhar
        run: |
          echo "O pipeline de CI/CD falhou. Por favor, verifique e corrija as etapas necessárias." | mail -s "CI/CD Pipeline Failed" ccasantos83@hotmail.com
