name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Deploy to test environment
        if: success()   # Executar somente se os passos anteriores forem bem-sucedidos
        run: |
          # Coloque aqui os comandos específicos para fazer o deploy da aplicação no ambiente de teste
          echo "Deploying application to test environment"
          # Por exemplo, você pode copiar os arquivos para um servidor via SSH
          scp -r build/* user@example.com:/path/to/test/environment

      - name: Notify on failure
        if: failure()   # Executar somente se algum dos passos anteriores falhar
        run: |
          echo "O pipeline de CI/CD falhou. Por favor, verifique e corrija as etapas necessárias." | mail -s "CI/CD Pipeline Failed" user@example.com
